### ISSUE TITLE
TODOs from March 31st Glimmer ST meeting

### ISSUE THREAD

**Issue by chancancode** [emberjs/core-notes#150]
- [x] Move tomdale/glimmer-website to glimmerjs org [@tomdale]
- [x] Move tildeio/glimmer to glimmerjs/glimmer-vm [@chancancode]
- [x] Make `@glimmer/application` depend on `@glimmer/component` [@tomdale]
- [x] Sync Github/NPM permissions for core team members [@locks]
- [ ] Stop publishing `glimmer-engine` on NPM [@tomdale]
- [x] Send Doodle for meeting times [@chancancode]
- [x] Propose replacing core team slack with Discord as a trial in next core team meeting [@wycats]
- [ ] "Fix nulls" (?) [@tomdale]
- [ ] File `arguments.length` issue against TypeScript [@krisselden]
- [x] Investigate issue with using web components with non-ES6 classes [@wycats]
- [x] Review glimmerjs/glimmer-application#40 [@tomdale]
- [ ] Add browser support policy to website [@tomdale]
- [x] Add back `expect()` to vm [@chadhietala]
- [ ] Use babel 6 in tests [@rwjblue]
- [ ] Fix type errors [@chancancode/@wycats]
- [ ] Extract @glimmer/utils into top-level packages, move `Opaque` there [@wycats]
- [x] Fix glimmerjs/* builds [@rwjblue]
- [x] Add dev/prod mode to glimmerjs/* [@rwjblue / @dgeb]
- [ ] Start `glimmerjs/glimmer-stdlib` [@chancancode]
- [ ] "peer dependencies" [@rwjblue]
- [ ] Implement emberjs/rfcs#213 [@chancancode]
- [ ] Refactor `getComponentDefinition` in emberjs/ember.js [@tomdale]
- [x] Change WC wrapper to generate `<$APP_NAME-app />` as the entry point (unless $APP_NAME already contain an "app" suffix?) to avoid collision with private collections [@tomdale]
- [x] Finish stack branch [@chancancode / @wycats]
- [x] Integrate stack branch into Ember [@chancancode / @wycats]
- [ ] Confirm complex-lists benchmark regression [@chadhietala]
- [ ] Implement capabilities mask [@chancancode / @wycats]
- [ ] Fix loc [@rwjblue]
- [ ] Strip partials from glimmerjs [@tomdale]
- [ ] Strip IE support from glimmerjs [@tomdale]

**Comment by tomdale** [comment]
Fix nulls === enable strict null checking in all Glimmer repos
