### ISSUE TITLE
rename docs-team folder to learning-team

### ISSUE THREAD

**Issue by mansona** [emberjs/core-notes#264]
Howdy folks 👋 

We have recently [documented our process](https://github.com/ember-learn/handbook/blob/master/team-leadership.md#responsibilities-would-include) for getting the Learning team core-notes into this repo and today is the first time that I have come to add minutes (it's my turn) 🎉 

I noticed that there is no `learning-team` folder and that our learning team minutes are instead in the `docs-team` folder. I don't fully understand the history of the learning team since I'm new, but I was under the impression that we very purposely don't call it a **docs-team** for various reasons that are probably spread over many videos on YouTube and blogs.

Is there any objection to renaming the folder from `docs-team` to `learning-team`?

**Comment by acorncom** [comment]
The context here is that the folder was named **before** the learning team became the learning team 😉 I have no objection in concept (it would be more consistent) but we’d also lose history in the process of the move. @locks can you explain your reaction here?

**Comment by mansona** [comment]
@acorncom what would you mean by "los[ing] history" in this case? if we do it as a normal git move then the history will be maintained from a file perspective.

If we want to represent the fact that the docs team "evolved" into the learning team we should probably only move files after the date it was made official.

I just think it's odd that I'm adding something to the docs-team folder. I am not a member of the docs team, I'm a member of the **learning** team 😂 and it matters what you name things 👍

**Comment by locks** [comment]
My objection is a recurring one, I am not keen on breaking URLs for what I perceive to be little gain in this instance.

**Comment by rwjblue** [comment]
I agree, many of these notes have been cross linked (in various comments, blog posts, etc). I think it would be totally great to start using the correct terminology going forward, and we could even _copy_ the contents into the correct place, but we shouldn't remove it from `docs-team`.

I think my concrete suggestion would be:

* Add a top level `learning-team` folder
* Start adding new content to `learning-team`
* Add a `docs-team/README.md` explaining that the folder is legacy and new items are added in `learning-team`.
* _Optionally_ fail CI if a new file is added to `docs-team` (helps us to not forget 😛)
* _Optionally_ copy all existing `docs-team` content into the new folder

What say y'all?

**Comment by rwjblue** [comment]
Also, FWIW, `learning-team` was coined back in May of 2016, so at least _some_ of the content here predates the newer term.

https://emberjs.com/blog/2016/05/19/introducing-subteams.html

We should decide if the content in the `learning-team` folder is just content _after_ that date, or if it was "retroactive".

**Comment by amyrlam** [comment]
Made this PR, please leave feedback, can make changes to get this closed! https://github.com/emberjs/core-notes/pull/273

**Comment by amyrlam** [comment]
Closed via https://github.com/emberjs/core-notes/pull/273
