### ISSUE TITLE
Can all new note files be added via PR please :)

### ISSUE THREAD

**Issue by workmanw** [emberjs/core-notes#38]
I really enjoy reading these. I watch this repo so that I can get notifications when new notes are added. Today I saw that the two fastboot-team notes weren't added via PR and thus I didn't get notified. I don't think there is a way to get Github alerts for every commit.

If it's not too much trouble, would you guys mind adding all new note files via PR. Even if they're merged right away.

**Comment by rwjblue** [comment]
I agree. I'll mention this to the rest of the team during our meeting tomorrow.

**Comment by workmanw** [comment]
@rwjblue Thank you.

**Comment by mixonic** [comment]
Strong agree.

I'll close this, but thanks for the ping!
