### ISSUE TITLE
Use 2 digits for all days

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/core-notes#49]
This is obviously a minor thing, but could the day values used in the naming convention always have two digits? This would help keep things in chronological order for those meetings that take place within the single-digit days of the month.

Ex:

```
february-11.md
february-19.md
february-4.md
```

Becomes:

```
february-04.md
february-11.md
february-19.md
```

Thanks for the consideration!

**Comment by wifelette** [comment]
+1, do you want to submit a PR to rename any old ones?

I don't anticipate any objections, but compliance could be an issue since we aren't working with templates yet :p That said, a meeting notes template is in the works, so that might get better quickly too :) 

cc @locks

**Comment by trentmwillis** [comment]
Sure, I'll submit a PR later today with the renaming.
